/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbms_project;

import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author madhulika
 */
public class UserProfile extends javax.swing.JFrame {
    int userid=0;
    database db=new database();
    DefaultTableModel model=new DefaultTableModel();
    DefaultTableModel rmModel=new DefaultTableModel();
    DefaultTableModel searchModel=new DefaultTableModel();
    DefaultTableModel buyReqModel=new DefaultTableModel();
    DefaultTableModel mybuyReqModel=new DefaultTableModel();

    /**
     * Creates new form UserProfile
     */
    public UserProfile() {
        initComponents();
    }
   

    UserProfile(String name, int userId) {
        
        initComponents();
        jLabel1.setText("Welcome "+name+" !");
        userid=userId;
        model=(DefaultTableModel) myBooksTable.getModel();
        rmModel=(DefaultTableModel) delBookTable.getModel();
        searchModel=(DefaultTableModel) srchTable.getModel();
        buyReqModel=(DefaultTableModel) buyReqTable.getModel();
        mybuyReqModel=(DefaultTableModel) myBuyReqTable.getModel();
        myBooksTab(model);
        myBooksTab(rmModel);
        buyRequestTab(buyReqModel);
        mybuyRequestTab(mybuyReqModel);
        delBookTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        srchTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        buyReqTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablayout = new javax.swing.JTabbedPane();
        addbook_tab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        isbn_tf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        title_tf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        author_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pub_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cp_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        price_tf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        desc_ta = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        genre_list = new javax.swing.JList<>();
        add_btn = new javax.swing.JButton();
        mybook_tab = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        myBooksTable = new javax.swing.JTable();
        buyreq_tab = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        buyReqTable = new javax.swing.JTable();
        accReq_btn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        mybuyreq_tab = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        myBuyReqTable = new javax.swing.JTable();
        delbook_tab = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        delBookTable = new javax.swing.JTable();
        del_btn = new javax.swing.JButton();
        search_tab = new javax.swing.JPanel();
        searchby_cb = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        titlesrch_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        genre_cb = new javax.swing.JComboBox<>();
        search_btn = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        srchTable = new javax.swing.JTable();
        view_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tablayout.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jLabel2.setText("ISBN");

        isbn_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isbn_tfKeyTyped(evt);
            }
        });

        jLabel3.setText("Title");

        jLabel4.setText("Author");

        author_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                author_tfKeyTyped(evt);
            }
        });

        jLabel5.setText("Publisher");

        pub_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pub_tfKeyTyped(evt);
            }
        });

        jLabel6.setText("Copies");

        cp_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cp_tfKeyTyped(evt);
            }
        });

        jLabel7.setText("Price");

        price_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                price_tfKeyTyped(evt);
            }
        });

        jLabel8.setText("Description");

        desc_ta.setColumns(20);
        desc_ta.setRows(5);
        jScrollPane2.setViewportView(desc_ta);

        jLabel9.setText("Genre");

        genre_list.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        genre_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Action and adventure", "Alternate history", "Anthology", "Art", "Autobiography", "Biography", "Chick lit", "Children's \t", "Comic book", "Coming-of-age", "Cookbook \t", "Crime", "Diary", "Dictionary", "Drama", "Encyclopedia", "Fairytale", "Fantasy", "Graphic novel \t", "Guide", "Health", "Historical fiction ", "History", "Horror", "Journal   ", "Math", "Memoir", "Mystery ", "Paranormal romance ", "Picture book ", "Poetry \t", "Political thriller", "Religion", "Review \t", "Romance \t", "Satire \t", "Science", "Science fiction \t", "Self help", "Short story \t", "Suspense \t", "Textbook", "Thriller", "Travel", "True crime", "Young adult " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(genre_list);

        add_btn.setText("Add");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addbook_tabLayout = new javax.swing.GroupLayout(addbook_tab);
        addbook_tab.setLayout(addbook_tabLayout);
        addbook_tabLayout.setHorizontalGroup(
            addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbook_tabLayout.createSequentialGroup()
                .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addbook_tabLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)))
                            .addGroup(addbook_tabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)))
                        .addGap(53, 53, 53)
                        .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isbn_tf)
                            .addComponent(title_tf)
                            .addComponent(author_tf)
                            .addComponent(pub_tf)
                            .addComponent(cp_tf)
                            .addComponent(price_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(add_btn)))
                .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel8))
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel9)))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        addbook_tabLayout.setVerticalGroup(
            addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addbook_tabLayout.createSequentialGroup()
                .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(isbn_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(title_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(author_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pub_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addbook_tabLayout.createSequentialGroup()
                        .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(cp_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(addbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(price_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(add_btn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addbook_tabLayout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        tablayout.addTab("Add Book", addbook_tab);

        myBooksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title ", "Author", "Price", "Copies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(myBooksTable);

        javax.swing.GroupLayout mybook_tabLayout = new javax.swing.GroupLayout(mybook_tab);
        mybook_tab.setLayout(mybook_tabLayout);
        mybook_tabLayout.setHorizontalGroup(
            mybook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mybook_tabLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        mybook_tabLayout.setVerticalGroup(
            mybook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mybook_tabLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        tablayout.addTab("My Books", mybook_tab);

        buyReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Buyer", "Total Price", "Copies", "Mob no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(buyReqTable);

        accReq_btn.setText("Accept");
        accReq_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accReq_btnActionPerformed(evt);
            }
        });

        jButton1.setText("Reject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buyreq_tabLayout = new javax.swing.GroupLayout(buyreq_tab);
        buyreq_tab.setLayout(buyreq_tabLayout);
        buyreq_tabLayout.setHorizontalGroup(
            buyreq_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyreq_tabLayout.createSequentialGroup()
                .addGroup(buyreq_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyreq_tabLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buyreq_tabLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(accReq_btn)
                        .addGap(94, 94, 94)
                        .addComponent(jButton1)))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        buyreq_tabLayout.setVerticalGroup(
            buyreq_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyreq_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(buyreq_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accReq_btn)
                    .addComponent(jButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tablayout.addTab("Buy Request", buyreq_tab);

        myBuyReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title", "Seller", "Price", "Copies", "Mob no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(myBuyReqTable);

        javax.swing.GroupLayout mybuyreq_tabLayout = new javax.swing.GroupLayout(mybuyreq_tab);
        mybuyreq_tab.setLayout(mybuyreq_tabLayout);
        mybuyreq_tabLayout.setHorizontalGroup(
            mybuyreq_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mybuyreq_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        mybuyreq_tabLayout.setVerticalGroup(
            mybuyreq_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mybuyreq_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tablayout.addTab("My Buy Requests", mybuyreq_tab);

        delBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Price", "Copies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(delBookTable);

        del_btn.setText("Delete");
        del_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout delbook_tabLayout = new javax.swing.GroupLayout(delbook_tab);
        delbook_tab.setLayout(delbook_tabLayout);
        delbook_tabLayout.setHorizontalGroup(
            delbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delbook_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(del_btn)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        delbook_tabLayout.setVerticalGroup(
            delbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delbook_tabLayout.createSequentialGroup()
                .addGroup(delbook_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(delbook_tabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(delbook_tabLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(del_btn)))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tablayout.addTab("Remove Book", delbook_tab);

        searchby_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Genre" }));

        jLabel10.setText("Search by");

        jLabel11.setText("Enter Title");

        jLabel12.setText("Genre");

        genre_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Action and adventure", "Alternate history", "Anthology", "Art", "Autobiography", "Biography", "Chick lit", "Children's \t", "Comic book", "Coming-of-age", "Cookbook \t", "Crime", "Diary", "Dictionary", "Drama", "Encyclopedia", "Fairytale", "Fantasy", "Graphic novel \t", "Guide", "Health", "Historical fiction ", "History", "Horror", "Journal   ", "Math", "Memoir", "Mystery ", "Paranormal romance ", "Picture book ", "Poetry \t", "Political thriller", "Religion", "Review \t", "Romance \t", "Satire \t", "Science", "Science fiction \t", "Self help", "Short story \t", "Suspense \t", "Textbook", "Thriller", "Travel", "True crime", "Young adult " }));

        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        srchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Title", "Author", "Publisher", "Price", "Copies", "userid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(srchTable);

        view_btn.setText("View");
        view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_tabLayout = new javax.swing.GroupLayout(search_tab);
        search_tab.setLayout(search_tabLayout);
        search_tabLayout.setHorizontalGroup(
            search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_tabLayout.createSequentialGroup()
                .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_tabLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(search_tabLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(searchby_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(search_tabLayout.createSequentialGroup()
                                .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(titlesrch_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                    .addComponent(genre_cb, 0, 1, Short.MAX_VALUE)))))
                    .addGroup(search_tabLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(search_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(view_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        search_tabLayout.setVerticalGroup(
            search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_tabLayout.createSequentialGroup()
                .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_tabLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchby_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(32, 32, 32)
                        .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(titlesrch_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(search_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(genre_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(search_btn)
                        .addGap(18, 18, 18)
                        .addComponent(view_btn))
                    .addGroup(search_tabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tablayout.addTab("Search", search_tab);

        jScrollPane1.setViewportView(tablayout);

        logout_btn.setText("Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_btn)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logout_btn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isbn_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbn_tfKeyTyped
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_isbn_tfKeyTyped

    private void cp_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cp_tfKeyTyped
         char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE))
       {
           evt.consume();
       }
    }//GEN-LAST:event_cp_tfKeyTyped

    private void price_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_tfKeyTyped
         char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE ||c=='.'))
       {
           evt.consume();
       }
    }//GEN-LAST:event_price_tfKeyTyped

    private void author_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_author_tfKeyTyped
      char c=evt.getKeyChar();
       SpecialChars sp=new SpecialChars();
       if(Character.isDigit(c) || sp.check(c))
       {
           evt.consume();
       }
    }//GEN-LAST:event_author_tfKeyTyped

    private void pub_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pub_tfKeyTyped
         char c=evt.getKeyChar();
       SpecialChars sp=new SpecialChars();
       if(Character.isDigit(c) || sp.check(c))
       {
           evt.consume();
       }
    }//GEN-LAST:event_pub_tfKeyTyped

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        String isbn=isbn_tf.getText();
        String title=title_tf.getText();
        String author=author_tf.getText();
        String pub=pub_tf.getText();
        String cp=cp_tf.getText();
        String price=price_tf.getText();
        String desc=desc_ta.getText();
        List<String> genre=genre_list.getSelectedValuesList();
       
        if(isbn.isEmpty() || title.isEmpty() || author.isEmpty() || cp.isEmpty() || price.isEmpty())
          JOptionPane.showMessageDialog(null,"Fields empty!");
       else if(isbn.length()!=10)
           JOptionPane.showMessageDialog(null,"ISBN format invalid!");
       else 
       {
           if(db.checkBookDetails(userid,isbn))
           {
           if(db.insertUserBook(userid,isbn,desc,price,cp) && db.insertBookGenre(userid,isbn,genre) && db.insertBookDetails(isbn,title,author,pub))
           {
             
               JOptionPane.showMessageDialog(null, "Added book successfully");
               myBooksTab(model);
               myBooksTab(rmModel);
           }
           else
               JOptionPane.showMessageDialog(null,"Book already exists!");
           }
           else
           {
               if(db.insertUserBook(userid,isbn,desc,price,cp) && db.insertBookGenre(userid,isbn,genre))
           {
               JOptionPane.showMessageDialog(null, "Added book successfully");
               myBooksTab(model);
               myBooksTab(rmModel);
           }
           else
               JOptionPane.showMessageDialog(null,"Book already exists!");
           }
       }
           
    }//GEN-LAST:event_add_btnActionPerformed

    private void del_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_btnActionPerformed
       db.delBook(userid,rmModel,delBookTable.getSelectedRow());
       myBooksTab(model);
       myBooksTab(rmModel);
    }//GEN-LAST:event_del_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        if(searchby_cb.getSelectedItem().equals("Title"))
        {
            String title=titlesrch_tf.getText();
            searchModel.getDataVector().removeAllElements();
            if(!db.searchTitle(userid,title,searchModel))
                JOptionPane.showMessageDialog(null, "No results found!");
        }
        else
        {
            String genre=(String) genre_cb.getSelectedItem();
            searchModel.getDataVector().removeAllElements();
            if(!db.searchGenre(userid,genre,searchModel))
                JOptionPane.showMessageDialog(null, "No results found");
        }
    }//GEN-LAST:event_search_btnActionPerformed

    private void view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_btnActionPerformed
       int row = srchTable.getSelectedRow();
       if(row!=-1)
       {
           new SearchResult(srchTable.getValueAt(row,0),srchTable.getValueAt(row, 1),
                   srchTable.getValueAt(row,2),srchTable.getValueAt(row, 3),
                   srchTable.getValueAt(row, 4),srchTable.getValueAt(row,5),
                   srchTable.getValueAt(row,6),userid,this).setVisible(true);
           this.setVisible(false);
       }
       else
           JOptionPane.showMessageDialog(null,"No result selected!");
    }//GEN-LAST:event_view_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        new LoginForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void accReq_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accReq_btnActionPerformed
      
        int row=buyReqTable.getSelectedRow();
      if(row!=-1)
      {
          if(db.accReq(userid,buyReqTable.getValueAt(row,1),buyReqTable.getValueAt(row, 0),buyReqTable.getValueAt(row,3)))
          {
              buyReqModel.removeRow(row);
              JOptionPane.showMessageDialog(null,"Accepted Successfully");
              myBooksTab(model);
              myBooksTab(rmModel);
          }
          else
              JOptionPane.showMessageDialog(null,"Accept Error!");
      }
      else
          JOptionPane.showMessageDialog(null,"No row selected!");
    }//GEN-LAST:event_accReq_btnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int row=buyReqTable.getSelectedRow();
        if(row!=-1)
        {
            if(db.rejReq(userid,buyReqTable.getValueAt(row, 1),buyReqTable.getValueAt(row, 0)))
            {
                buyReqModel.removeRow(row);
                JOptionPane.showMessageDialog(null,"Rejected request!");
            }
            else
                JOptionPane.showMessageDialog(null,"Error during rejecting!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void myBooksTab(DefaultTableModel model)
    {
        db.myBooks(userid,model);
    }
    
   void buyRequestTab(DefaultTableModel model)
   {
      db.buyReqDisp(userid, model);
   }
   
   void mybuyRequestTab(DefaultTableModel model)
   {
       db.mybuyReqTab(userid,model);
   }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accReq_btn;
    private javax.swing.JButton add_btn;
    private javax.swing.JPanel addbook_tab;
    private javax.swing.JTextField author_tf;
    private javax.swing.JTable buyReqTable;
    private javax.swing.JPanel buyreq_tab;
    private javax.swing.JTextField cp_tf;
    private javax.swing.JTable delBookTable;
    private javax.swing.JButton del_btn;
    private javax.swing.JPanel delbook_tab;
    private javax.swing.JTextArea desc_ta;
    private javax.swing.JComboBox<String> genre_cb;
    private javax.swing.JList<String> genre_list;
    private javax.swing.JTextField isbn_tf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JButton logout_btn;
    private javax.swing.JTable myBooksTable;
    private javax.swing.JTable myBuyReqTable;
    private javax.swing.JPanel mybook_tab;
    private javax.swing.JPanel mybuyreq_tab;
    private javax.swing.JTextField price_tf;
    private javax.swing.JTextField pub_tf;
    private javax.swing.JButton search_btn;
    private javax.swing.JPanel search_tab;
    private javax.swing.JComboBox<String> searchby_cb;
    private javax.swing.JTable srchTable;
    private javax.swing.JTabbedPane tablayout;
    private javax.swing.JTextField title_tf;
    private javax.swing.JTextField titlesrch_tf;
    private javax.swing.JButton view_btn;
    // End of variables declaration//GEN-END:variables

   
}
